[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"
font = "sans serif"
base = "light"

[server]
maxUploadSize = 200
maxMessageSize = 200

[browser]
gatherUsageStats = false 